### ISSUE TITLE
[BUG]: Bug report template does not have all system/version information that is required

### ISSUE THREAD

**Issue by gallacher** [dell/karavi-topology#63]
**Describe the bug**
The bug report template should be updated to specify the following required system information:
- Kubernetes Version: [e.g. 1.18]
- karavi-topology Version: [e.g. 0.1.0-pre-release]
- Grafana Version: [e.g. 7.3.2]
- Grafana Dashboard Title: [e.g. Kubernetes Admin Dashboard]
- Grafana Datatable Panel plugin configuration (can be provided as a screenshot)
- Grafana JSON Datasource configuration (can be provided as a screenshot)

**To Reproduce**
N/A

**Expected behavior**
The new system information should appear in the Bug report template

**Screenshots**
N/A

**Logs**
N/A

**System Information (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ioeicicdsvc** [comment]
link: 1667

**Comment by gallacher** [comment]
test comment
