### ISSUE TITLE
[BUG]: The Grafana JSON datasource default name is incorrect

### ISSUE THREAD

**Issue by gallacher** [dell/karavi-topology#67]
**Describe the bug**
The default name for the JSON datasource is JSON.  This needs to be changed to Karavi-Topology.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Logs**
N/A

**System Information (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ioeicicdsvc** [comment]
link: 1686

**Comment by ioeicicdsvc** [comment]
This issue has been copied to dell/karavi as issue https://github.com/dell/karavi/issues/18
